- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Free Trial(c81157b5-09ef-4e23-8c08-c64fbe5d34eb)'
    azureResourceGroup: 'test'
    kubernetesCluster: 'myAKSCluster'
    namespace: 'default'
    manifests: 'azure-pipelines.yml'